-- One-shot population script for trivia_subcategories from the view export
-- Safe to rerun: upserts are keyed by (category_type, category_slug, slug).

begin;

insert into public.trivia_subcategories (category_type, category_slug, subcategory, slug, description, question_count, sort_order, is_active)
values
('trivias', 'cartoons-anime', 'Mystery Cartoons', 'mystery-cartoons', null, 11, 1, true),
('trivias', 'cartoons-anime', 'Cartoon Network', 'cartoon-network', null, 9, 2, true),
('trivias', 'cartoons-anime', 'Sci-Fi Western', 'sci-fi-western', null, 5, 3, true),
('trivias', 'cartoons-anime', 'Studio Ghibli', 'studio-ghibli', null, 5, 4, true),
('trivias', 'cartoons-anime', 'Spy Comedy', 'spy-comedy', null, 2, 5, true),
('trivias', 'cartoons-anime', 'Isekai Comedy', 'isekai-comedy', null, 1, 6, true),
('trivias', 'cartoons-anime', 'Isekai/Time Loop', 'isekai-time-loop', null, 1, 7, true),
('trivias', 'cartoons-anime', 'Philosophical Sci-Fi', 'philosophical-sci-fi', null, 1, 8, true),
('trivias', 'cartoons-anime', 'Preschool Animation', 'preschool-animation', null, 1, 9, true),
('trivias', 'cartoons-anime', 'Supernatural Academy', 'supernatural-academy', null, 1, 10, true),
('trivias', 'cartoons-anime', 'Supernatural Romance', 'supernatural-romance', null, 1, 11, true),
('trivias', 'cartoons-anime', 'Video Game Adaptations', 'video-game-adaptations', null, 1, 12, true),
('trivias', 'inventions', 'Food & Kitchen', 'food-kitchen', null, 30, 1, true),
('trivias', 'inventions', 'Mechanical & Industrial', 'mechanical-industrial', null, 30, 2, true),
('trivias', 'computers', 'Security', 'security', null, 36, 1, true),
('trivias', 'computers', 'Hardware', 'hardware', null, 25, 2, true),
('trivias', 'computers', 'Multimedia', 'multimedia', null, 4, 3, true),
('trivias', 'computers', 'Companies', 'companies', null, 2, 4, true),
('trivias', 'animals', 'Birds', 'birds', null, 62, 1, true),
('trivias', 'animals', 'Marine Life', 'marine-life', null, 56, 2, true),
('trivias', 'animals', 'Collective Nouns', 'collective-nouns', null, 51, 3, true),
('trivias', 'religion-spirituality', 'Buddhism', 'buddhism', null, 31, 1, true),
('trivias', 'religion-spirituality', 'Islam', 'islam', null, 31, 2, true),
('trivias', 'religion-spirituality', 'Judaism', 'judaism', null, 30, 3, true),
('trivias', 'religion-spirituality', 'Baha’i', 'baha-i', null, 4, 4, true),
('trivias', 'religion-spirituality', 'Confucianism', 'confucianism', null, 3, 5, true),
('trivias', 'board-games', 'Thematic', 'thematic', null, 4, 1, true),
('trivias', 'board-games', 'Party', 'party', null, 3, 2, true),
('trivias', 'movies', 'Animation', 'animation', null, 59, 1, true),
('trivias', 'movies', 'Horror', 'horror', null, 58, 2, true),
('trivias', 'movies', 'Science Fiction', 'science-fiction', null, 55, 3, true),
('trivias', 'movies', 'New Releases', 'new-releases', null, 15, 4, true),
('trivias', 'movies', 'International Cinema', 'international-cinema', null, 1, 5, true),
('trivias', 'science', 'Nobel Prize', 'nobel-prize', null, 30, 1, true),
('trivias', 'science', 'Meteorology', 'meteorology', null, 15, 2, true),
('trivias', 'science', 'Oceanography', 'oceanography', null, 15, 3, true),
('trivias', 'business', 'Advertising & Branding', 'advertising-branding', null, 69, 1, true),
('trivias', 'business', 'Startup Culture & Logistics', 'startup-culture-logistics', null, 48, 2, true),
('trivias', 'business', 'Tech & Product History', 'tech-product-history', null, 30, 3, true),
('trivias', 'famous-firsts', 'Sports', 'sports', null, 4, 1, true),
('trivias', 'famous-firsts', 'Literature', 'literature', null, 2, 2, true),
('trivias', 'famous-firsts', 'Mathematics', 'mathematics', null, 1, 3, true),
('trivias', 'famous-firsts', 'Movies & Animation', 'movies-animation', null, 1, 4, true),
('trivias', 'famous-firsts', 'Politics & Law', 'politics-law', null, 1, 5, true),
('trivias', 'famous-firsts', 'Space & Animals', 'space-animals', null, 1, 6, true),
('trivias', 'famous-firsts', 'Tech & Culture', 'tech-culture', null, 1, 7, true),
('trivias', 'celebrities', 'TV', 'tv', null, 6, 1, true),
('trivias', 'celebrities', 'Pop Culture', 'pop-culture', null, 2, 2, true),
('trivias', 'tv', 'Drama', 'drama', null, 83, 1, true),
('trivias', 'tv', 'Animated', 'animated', null, 30, 2, true),
('trivias', 'tv', 'Fantasy', 'fantasy', null, 17, 3, true),
('trivias', 'tv', 'Emmy Awards', 'emmy-awards', null, 10, 4, true),
('trivias', 'tv', 'Reality TV', 'reality-tv', null, 4, 5, true),
('trivias', 'tv', 'Streaming', 'streaming', null, 3, 6, true),
('trivias', 'economics', 'Digital', 'digital', null, 6, 1, true),
('trivias', 'economics', 'Awards', 'awards', null, 2, 2, true),
('trivias', 'architecture', 'Architects', 'architects', null, 22, 1, true),
('trivias', 'architecture', 'Image Based', 'image-based', null, 20, 2, true),
('trivias', 'architecture', 'Skyscrapers', 'skyscrapers', null, 4, 3, true),
('trivias', 'architecture', 'Ancient Rome', 'ancient-rome', null, 3, 4, true),
('trivias', 'architecture', 'Cathedrals', 'cathedrals', null, 3, 5, true),
('trivias', 'architecture', 'Landmarks', 'landmarks', null, 3, 6, true),
('trivias', 'architecture', 'Defensive Walls', 'defensive-walls', null, 1, 7, true),
('trivias', 'architecture', 'Government', 'government', null, 1, 8, true),
('trivias', 'architecture', 'Performing Arts', 'performing-arts', null, 1, 9, true),
('trivias', 'architecture', 'Public Art', 'public-art', null, 1, 10, true),
('trivias', 'architecture', 'Religious', 'religious', null, 1, 11, true),
('trivias', 'architecture', 'Wooden Architecture', 'wooden-architecture', null, 1, 12, true),
('trivias', 'history', 'Economic Disasters', 'economic-disasters', null, 36, 1, true),
('trivias', 'history', 'Medieval Wars', 'medieval-wars', null, 30, 2, true),
('trivias', 'history', 'Monarchy', 'monarchy', null, 30, 3, true),
('trivias', 'history', 'Medieval India', 'medieval-india', null, 15, 4, true),
('trivias', 'history', 'Names', 'names', null, 15, 5, true),
('trivias', 'music', 'Pop', 'pop', null, 55, 1, true),
('trivias', 'music', 'Music Theory & Instruments', 'music-theory-instruments', null, 32, 2, true),
('trivias', 'geography', 'Country Capitals', 'country-capitals', null, 147, 1, true),
('trivias', 'geography', 'Flags', 'flags', null, 59, 2, true),
('trivias', 'geography', 'People and Cultures', 'people-and-cultures', null, 50, 3, true),
('trivias', 'sports', 'Sports History', 'sports-history', null, 52, 1, true),
('trivias', 'sports', 'Extreme & Niche Sports', 'extreme-niche-sports', null, 46, 2, true),
('trivias', 'sports', 'Olympics', 'olympics', null, 11, 3, true),
('trivias', 'sports', 'Paralympics', 'paralympics', null, 2, 4, true),
('trivias', 'literature', 'Closing Lines', 'closing-lines', null, 30, 1, true),
('trivias', 'mythology', 'Celtic', 'celtic', null, 13, 1, true),
('trivias', 'mythology', 'Mesopotamian', 'mesopotamian', null, 6, 2, true),
('trivias', 'mythology', 'Slavic', 'slavic', null, 3, 3, true),
('trivias', 'mythology', 'Persian', 'persian', null, 1, 4, true),
('trivias', 'languages', 'Idioms', 'idioms', null, 58, 1, true),
('trivias', 'languages', 'Word Origins', 'word-origins', null, 39, 2, true),
('trivias', 'fashion', 'Hair, Makeup & Beauty', 'hair-makeup-beauty', null, 30, 1, true),
('trivias', 'famous-quotes', 'Literature', 'literature', null, 30, 1, true),
('trivias', 'famous-quotes', 'Religious', 'religious', null, 1, 2, true),
('trivias', 'video-games', 'Action', 'action', null, 5, 1, true),
('trivias', 'video-games', 'Metroidvania', 'metroidvania', null, 2, 2, true),
('trivias', 'video-games', 'Arcade', 'arcade', null, 1, 3, true),
('trivias', 'law-politics', 'International Organizations', 'international-organizations', null, 27, 1, true),
('trivias', 'law-politics', 'Global Governance', 'global-governance', null, 12, 2, true),
('trivias', 'acronyms', 'Internet', 'internet', null, 2, 1, true),
('trivias', 'acronyms', 'Health', 'health', null, 1, 2, true),
('trivias', 'arts', 'Renaissance', 'renaissance', null, 63, 1, true)
on conflict (category_type, category_slug, slug) do update set
  subcategory = excluded.subcategory,
  question_count = excluded.question_count,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();

commit;
