-- Trivia category metadata for both daily-trivias and trivias
-- Apply in Supabase SQL editor or as a migration.

create type if not exists public.trivia_category_type as enum ('daily-trivias', 'trivias');

create table if not exists public.trivia_categories (
  id bigint generated by default as identity primary key,
  slug text not null,
  category_type public.trivia_category_type not null,
  title text not null,
  description text not null,
  long_description text not null default '',
  learning_points jsonb not null default '[]'::jsonb,
  faq_items jsonb not null default '[]'::jsonb,
  related jsonb not null default '[]'::jsonb,
  keywords jsonb not null default '[]'::jsonb,
  og_image text,
  display_name text,
  icon text,
  color text,
  show_printable_quiz_cta boolean not null default true,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists trivia_categories_type_slug_uidx
  on public.trivia_categories (category_type, slug);

create index if not exists trivia_categories_type_active_sort_idx
  on public.trivia_categories (category_type, is_active, sort_order, title);

create table if not exists public.trivia_subcategories (
  id bigint generated by default as identity primary key,
  category_type public.trivia_category_type not null default 'trivias',
  category_slug text not null,
  subcategory text not null,
  slug text not null,
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category_type, category_slug, slug),
  foreign key (category_type, category_slug)
    references public.trivia_categories (category_type, slug)
    on delete cascade
);

create index if not exists trivia_subcategories_type_category_active_sort_idx
  on public.trivia_subcategories (category_type, category_slug, is_active, sort_order);

create index if not exists trivia_subcategories_category_active_sort_idx
  on public.trivia_subcategories (category_slug, is_active, sort_order);

create index if not exists trivia_subcategories_category_slug_idx
  on public.trivia_subcategories (category_slug, slug);

create or replace view public.trivia_subcategories_enriched_view as
select
  s.category_type,
  s.category_slug as category,
  s.category_slug,
  s.subcategory,
  s.slug,
  s.description,
  v.question_count,
  s.sort_order,
  s.is_active,
  s.created_at,
  s.updated_at
from public.trivia_subcategories s
left join public.trivia_subcategories_view v
  on s.category_slug = v.category
  and s.subcategory = v.subcategory;

alter table public.trivia_categories enable row level security;
alter table public.trivia_subcategories enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'trivia_categories'
      and policyname = 'Public read trivia categories'
  ) then
    create policy "Public read trivia categories"
      on public.trivia_categories
      for select
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'trivia_subcategories'
      and policyname = 'Public read trivia subcategories'
  ) then
    create policy "Public read trivia subcategories"
      on public.trivia_subcategories
      for select
      using (true);
  end if;
end $$;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_trivia_categories_updated_at on public.trivia_categories;
create trigger touch_trivia_categories_updated_at
before update on public.trivia_categories
for each row execute function public.touch_updated_at();

drop trigger if exists touch_trivia_subcategories_updated_at on public.trivia_subcategories;
create trigger touch_trivia_subcategories_updated_at
before update on public.trivia_subcategories
for each row execute function public.touch_updated_at();
