[build]
  # Clean build with cache and sensitive file cleanup
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_SKIP_PACKAGE_INSTALL = "false"
  NEXT_PRIVATE_TARGET = "server"
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

  # SWC configuration
  NEXT_DISABLE_BUILT_IN_SWC = "false"
  SWC_PLATFORM = "linux"

  # Security optimizations
  NEXT_TELEMETRY_DISABLED = "1"
  GENERATE_SOURCEMAP = "false"
  
  # Secrets scanning configuration - moved to build.environment
  SECRETS_SCAN_OMIT_PATHS = ".next/*,.netlify/*"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_FIREBASE_API_KEY,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,NEXT_PUBLIC_FIREBASE_PROJECT_ID,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,NEXT_PUBLIC_FIREBASE_APP_ID,NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,NEXT_PUBLIC_GA_ID,NEXT_PUBLIC_ADSENSE_ID,NEXT_PUBLIC_ADSENSE_SLOT_HEADER,NEXT_PUBLIC_ADSENSE_SLOT_SQUARE,NEXT_PUBLIC_ADSENSE_SLOT_MULTIPLEX,NEXT_PUBLIC_FACEBOOK_APP_ID,CONTENTFUL_SPACE_ID,CONTENTFUL_ACCESS_TOKEN,GOOGLE_ID,GOOGLE_SECRET,NEXTAUTH_SECRET"

# Cache configuration
[build.cache]
  paths = [
    "node_modules/.cache",
    ".next/cache"
  ]
  exclude = [
    ".next/cache/webpack",
    ".next/static/chunks/**/*.js",
    ".next/static/**/*.map"
  ]

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "interest-cohort=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' www.googletagmanager.com www.google-analytics.com; connect-src 'self' www.google-analytics.com; img-src 'self' data: www.google-analytics.com; style-src 'self' 'unsafe-inline'; frame-src 'self'"

# Static asset caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Image optimization redirects
[[redirects]]
  from = "/_next/image/"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  query = {url = ":url", w = ":width", q = ":quality"}

[[redirects]]
  from = "/_next/image/*"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  query = {url = ":url", w = ":width", q = ":quality"}

[[redirects]]
  from = "/_ipx/*"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  query = {url = ":url", w = ":width", q = ":quality"}

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200