export interface BrainwaveWarmupPuzzle {
  id: string;
  clue: string;
  answer: string;
  factoid: string;
  category: string;
  hints?: string[];
}

export const BRAINWAVE_WARMUPS: Record<string, BrainwaveWarmupPuzzle[]> = {
  plotle: [
    {
      id: 'plotle-warmup-1',
      clue: 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO. (Directed by Christopher Nolan, 2010)',
      answer: 'Inception',
      factoid: 'Christopher Nolan spent nearly ten years writing the screenplay for Inception before pitching it to Warner Bros.',
      category: 'Sci-Fi / Action',
      hints: ['Leonardo DiCaprio', 'Dream within a dream', 'Spinning top'],
    },
    {
      id: 'plotle-warmup-2',
      clue: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. (1994, based on a Stephen King novella)',
      answer: 'The Shawshank Redemption',
      factoid: 'Despite a modest initial box office run, the film became one of the most beloved and highest-rated films in cinema history.',
      category: 'Drama',
      hints: ['Tim Robbins', 'Morgan Freeman', 'Rock hammer'],
    },
    {
      id: 'plotle-warmup-3',
      clue: 'A meek hobbit and eight companions set out on a perilous journey to destroy a powerful ring in the fires of Mount Doom. (Directed by Peter Jackson, 2001)',
      answer: 'The Lord of the Rings: The Fellowship of the Ring',
      factoid: 'The entire Lord of the Rings trilogy was filmed simultaneously across more than 150 locations in New Zealand.',
      category: 'Fantasy / Adventure',
      hints: ['Frodo Baggins', 'Gandalf', 'Middle-earth'],
    },
  ],
  capitale: [
    {
      id: 'capitale-warmup-1',
      clue: 'Situated in the Andes mountain range at an elevation of 3,640 meters (11,942 ft), this city is widely recognized as the highest administrative capital in the world.',
      answer: 'La Paz, Bolivia',
      factoid: 'While Sucre is the constitutional capital of Bolivia, La Paz serves as the seat of government and executive branch.',
      category: 'South America',
      hints: ['Elevation: 3,640m', 'Mi Teleférico cable car', 'Andes Mountains'],
    },
    {
      id: 'capitale-warmup-2',
      clue: 'Located on the banks of the Danube River, this capital was formed in 1873 by unifying two distinct historic towns on opposite sides of the river.',
      answer: 'Budapest, Hungary',
      factoid: 'The city was officially created by merging Buda and Óbuda on the west bank with Pest on the east bank.',
      category: 'Europe',
      hints: ['Chain Bridge', 'Thermal Baths', 'Danube River'],
    },
    {
      id: 'capitale-warmup-3',
      clue: 'This planned capital city was designed by architect Lúcio Costa and inaugurated in 1960 to replace Rio de Janeiro as the national seat of government.',
      answer: 'Brasília, Brazil',
      factoid: 'When viewed from above, Brasília was purposefully shaped like an airplane or large bird.',
      category: 'South America',
      hints: ['Oscar Niemeyer architecture', 'Inaugurated 1960', 'Federal District'],
    },
  ],
  historidle: [
    {
      id: 'historidle-warmup-1',
      clue: 'On July 20, 1969, this crewed NASA spaceflight touched down on the lunar surface at the Sea of Tranquility, fulfilling a national goal set earlier in the decade.',
      answer: 'Apollo 11 Moon Landing',
      factoid: 'An estimated 650 million people worldwide watched Neil Armstrong’s televised first steps on the lunar surface.',
      category: '20th Century Space Exploration',
      hints: ['Neil Armstrong', 'Buzz Aldrin', 'Eagle Lunar Module'],
    },
    {
      id: 'historidle-warmup-2',
      clue: 'Signed in June 1215 at Runnymede near Windsor, this historic charter granted by King John established the principle that everyone, even the king, is subject to the law.',
      answer: 'Magna Carta',
      factoid: 'Only four original 1215 exemplars of Magna Carta survive today — two in the British Library, one in Salisbury Cathedral, and one in Lincoln Castle.',
      category: 'Medieval History',
      hints: ['King John', '1215', 'Baronial revolt'],
    },
    {
      id: 'historidle-warmup-3',
      clue: 'Discovered by Howard Carter in November 1922 in the Valley of the Kings, this nearly intact royal tomb contained over 5,000 precious artifacts and a golden death mask.',
      answer: 'Tomb of Tutankhamun',
      factoid: 'The discovery sparked a global wave of Egyptomania and renewed fascination with ancient Egyptian civilization in the 1920s.',
      category: 'Ancient History',
      hints: ['Valley of the Kings', 'Howard Carter', 'Golden mask'],
    },
  ],
  celebrile: [
    {
      id: 'celebrile-warmup-1',
      clue: 'Famous scientist and theoretical physicist born in Ulm, Germany, who won the 1921 Nobel Prize in Physics for his explanation of the photoelectric effect.',
      answer: 'Albert Einstein',
      factoid: 'Einstein famously played the violin and once remarked that if he were not a physicist, he would probably be a musician.',
      category: 'Science & Physics',
      hints: ['General Relativity', 'E=mc²', 'Princeton Institute for Advanced Study'],
    },
    {
      id: 'celebrile-warmup-2',
      clue: 'Iconic Mexican painter known for her many portraits, self-portraits, and works inspired by the nature and artifacts of Mexico, painted in Casa Azul.',
      answer: 'Frida Kahlo',
      factoid: '55 of Kahlo’s 143 paintings are self-portraits, which she often painted while recovering in bed using an easel built into her canopy.',
      category: 'Art & Culture',
      hints: ['Coyoacán', 'Surrealism / Folk Art', 'Diego Rivera'],
    },
    {
      id: 'celebrile-warmup-3',
      clue: 'Legendary Jamaican track and field sprinter who won eight Olympic gold medals and holds the world record for the 100-meter sprint at 9.58 seconds.',
      answer: 'Usain Bolt',
      factoid: 'Bolt set his 100m world record of 9.58 seconds at the 2009 World Athletics Championships in Berlin, reaching a top speed of 27.78 mph.',
      category: 'Sports & Athletics',
      hints: ['Lightning Bolt pose', 'Berlin 2009', '100m & 200m World Records'],
    },
  ],
  songle: [
    {
      id: 'songle-warmup-1',
      clue: 'Opening Lyric: "Is this the real life? Is this just fantasy? Caught in a landslide, no escape from reality." (Released in 1975)',
      answer: 'Bohemian Rhapsody (Queen)',
      factoid: 'Freddie Mercury composed the multi-part epic, which features opera, ballad, and hard rock sections without a traditional chorus.',
      category: 'Rock / Classic Hits',
      hints: ['Freddie Mercury', 'A Night at the Opera', 'Scaramouche'],
    },
    {
      id: 'songle-warmup-2',
      clue: 'Opening Lyric: "Just a small town girl, livin\' in a lonely world. She took the midnight train goin\' anywhere." (Released in 1981)',
      answer: 'Don\'t Stop Believin\' (Journey)',
      factoid: 'The song gained a massive second wave of popularity after being featured in the iconic final scene of The Sopranos in 2007.',
      category: '80s Rock',
      hints: ['Steve Perry', 'Escape Album', 'Streetlights, people'],
    },
    {
      id: 'songle-warmup-3',
      clue: 'Opening Lyric: "Load up on guns, bring your friends. It\'s fun to lose and to pretend." (Released in 1991)',
      answer: 'Smells Like Teen Spirit (Nirvana)',
      factoid: 'The breakthrough track from Nevermind propelled grunge music into mainstream culture in the early 1990s.',
      category: '90s Grunge / Alternative',
      hints: ['Kurt Cobain', 'Nevermind', 'Seattle Sound'],
    },
  ],
  literale: [
    {
      id: 'literale-warmup-1',
      clue: 'Opening Line: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife." (1813)',
      answer: 'Pride and Prejudice by Jane Austen',
      factoid: 'The novel was originally written under the working title "First Impressions" before being revised and published in 1813.',
      category: 'Classic Literature',
      hints: ['Elizabeth Bennet', 'Mr. Darcy', 'Longbourn'],
    },
    {
      id: 'literale-warmup-2',
      clue: 'Opening Line: "Call me Ishmael. Some years ago—never mind how long precisely—having little or no money in my purse..." (1851)',
      answer: 'Moby-Dick by Herman Melville',
      factoid: 'The book opens with Ishmael boarding the whaling ship Pequod under the command of the monomaniacal Captain Ahab.',
      category: 'American Literature',
      hints: ['Captain Ahab', 'The Pequod', 'Great White Whale'],
    },
    {
      id: 'literale-warmup-3',
      clue: 'Opening Line: "It was a bright cold day in April, and the clocks were striking thirteen." (1949)',
      answer: 'Nineteen Eighty-Four by George Orwell',
      factoid: 'George Orwell coined terms like "Big Brother", "Doublethink", "Thoughtcrime", and "Newspeak" in this dystopian masterpiece.',
      category: 'Dystopian Fiction',
      hints: ['Winston Smith', 'Big Brother', 'Oceania'],
    },
  ],
  creaturedle: [
    {
      id: 'creaturedle-warmup-1',
      clue: 'A large marine mammal known as the "sea cow", this gentle herbivore grazes on seagrass in warm shallow coastal waters and rivers.',
      answer: 'Manatee',
      factoid: 'Despite their aquatic lifestyle, manatees are most closely related evolutionarily to elephants and hyraxes.',
      category: 'Marine Mammals',
      hints: ['Herbivore', 'Slow-moving', 'Florida springs & Caribbean'],
    },
    {
      id: 'creaturedle-warmup-2',
      clue: 'The fastest land animal on Earth, capable of accelerating from 0 to 60 mph in under three seconds with specialized non-retractable claws for traction.',
      answer: 'Cheetah',
      factoid: 'Cheetahs use their long, muscular tail like a rudder on a boat to make sharp turns while sprinting at high speeds.',
      category: 'African Wildlife / Felines',
      hints: ['Tear stripes', 'Spotted coat', 'Savannah predator'],
    },
    {
      id: 'creaturedle-warmup-3',
      clue: 'An egg-laying mammal native to eastern Australia with a duck-like bill, beaver-like tail, and venomous spurs on male hind legs.',
      answer: 'Platypus',
      factoid: 'When European naturalists first examined a preserved platypus body in 1799, many believed it was an elaborate hoax stitched together.',
      category: 'Monotremes',
      hints: ['Semi-aquatic', 'Electrolocation', 'Egg-laying mammal'],
    },
  ],
  foodle: [
    {
      id: 'foodle-warmup-1',
      clue: 'A traditional Neapolitan pizza topped with simple San Marzano tomatoes, fresh mozzarella cheese, fresh basil, and extra virgin olive oil.',
      answer: 'Pizza Margherita',
      factoid: 'According to culinary tradition, it was created in 1889 by pizzaiolo Raffaele Esposito to represent the colors of the Italian flag (red, white, green).',
      category: 'Italian Cuisine',
      hints: ['Naples origin', 'Wood-fired oven', 'Italian flag colors'],
    },
    {
      id: 'foodle-warmup-2',
      clue: 'A beloved Spanish rice dish originally from Valencia, prepared in a wide shallow pan with saffron, vegetables, and meat or seafood.',
      answer: 'Paella',
      factoid: 'The crispy, caramelized crust of rice that forms at the bottom of a traditional paella pan is called "socarrat".',
      category: 'Spanish Cuisine',
      hints: ['Saffron rice', 'Valencia', 'Socarrat crust'],
    },
    {
      id: 'foodle-warmup-3',
      clue: 'A fragrant Thai soup balancing spicy, sour, and savory flavors, made with lemongrass, kaffir lime leaves, galangal, lime juice, and prawns.',
      answer: 'Tom Yum Goong',
      factoid: '"Tom" refers to the boiling process, while "Yum" refers to a spicy and sour Thai salad, and "Goong" means shrimp or prawns.',
      category: 'Thai Cuisine',
      hints: ['Lemongrass & galangal', 'Spicy & sour broth', 'Prawn soup'],
    },
  ],
  landmarkdle: [
    {
      id: 'landmarkdle-warmup-1',
      clue: 'An ivory-white marble mausoleum on the south bank of the Yamuna river in Agra, commissioned in 1632 by Mughal emperor Shah Jahan.',
      answer: 'Taj Mahal',
      factoid: 'The monument was designated a UNESCO World Heritage Site in 1983 as "the jewel of Muslim art in India".',
      category: 'Monuments / Architecture',
      hints: ['Agra, India', 'Mughal Architecture', 'Mumtaz Mahal'],
    },
    {
      id: 'landmarkdle-warmup-2',
      clue: 'A 15th-century Inca citadel situated on a mountain ridge 2,430 meters (7,970 ft) above sea level in the Eastern Cordillera of southern Peru.',
      answer: 'Machu Picchu',
      factoid: 'Built around 1450 for the Inca emperor Pachacuti, the citadel was brought to international attention in 1911 by Hiram Bingham.',
      category: 'Ancient Wonders',
      hints: ['Inca Empire', 'Sacred Valley', 'Andes Mountains'],
    },
    {
      id: 'landmarkdle-warmup-3',
      clue: 'A wrought-iron lattice tower on the Champ de Mars in Paris, constructed from 1887 to 1889 as the entrance arch to the 1889 World\'s Fair.',
      answer: 'Eiffel Tower',
      factoid: 'The tower was initially criticized by leading French artists and intellectuals, but has since become the global cultural icon of France.',
      category: 'Modern Architecture',
      hints: ['Gustave Eiffel', 'Champ de Mars', '330 meters tall'],
    },
  ],
  inventionle: [
    {
      id: 'inventionle-warmup-1',
      clue: 'Developed in the mid-15th century in Mainz, Germany, this mechanical device utilized movable metal type to mass-produce printed books.',
      answer: 'Gutenberg Printing Press',
      factoid: 'Johannes Gutenberg\'s movable type printing press ignited the Printing Revolution and played a pivotal role in the spread of the Renaissance and Reformation.',
      category: 'Communication & Printing',
      hints: ['Johannes Gutenberg', 'Mainz, 1440s', 'Movable metal type'],
    },
    {
      id: 'inventionle-warmup-2',
      clue: 'Discovered by Scottish physician Alexander Fleming in 1928, this revolutionary antibiotic substance was derived from Penicillium chrysogenum mold.',
      answer: 'Penicillin',
      factoid: 'Fleming famously noticed a halo of inhibited bacterial growth around a mold contamination in a Petri dish after returning from vacation.',
      category: 'Medicine & Healthcare',
      hints: ['Alexander Fleming', '1928', 'Antibiotic medicine'],
    },
    {
      id: 'inventionle-warmup-3',
      clue: 'Patented in 1876, this acoustic-to-electric telecommunication device converted sound waves into electrical signals transmitted through copper wire.',
      answer: 'Telephone',
      factoid: 'Alexander Graham Bell\'s first historic transmitted sentence was: "Mr. Watson—Come here—I want to see you."',
      category: 'Telecommunications',
      hints: ['Alexander Graham Bell', '1876', 'Thomas Watson'],
    },
  ],
  synonymle: [
    {
      id: 'synonymle-warmup-1',
      clue: 'Find the high-vocabulary synonym: "Describing something so fleeting, transient, or short-lived that it lasts for only a very short time."',
      answer: 'Ephemeral (Transient / Fleeting)',
      factoid: 'From the Greek word "ephemeros", literally meaning "lasting only for a day".',
      category: 'Vocabulary / Linguistics',
      hints: ['Starting with E', 'Opposite of eternal', 'Fleeting nature'],
    },
    {
      id: 'synonymle-warmup-2',
      clue: 'Find the synonym: "Extremely meticulous, showing great attention to detail and demanding high standards of cleanliness or precision."',
      answer: 'Fastidious (Meticulous / Punctilious)',
      factoid: 'A fastidious person is not easily pleased and pays scrupulous attention to every detail.',
      category: 'Vocabulary / Linguistics',
      hints: ['Starting with F', 'Opposite of careless', 'Painstaking accuracy'],
    },
    {
      id: 'synonymle-warmup-3',
      clue: 'Find the synonym: "Present, appearing, or found everywhere simultaneously; existing in all places at once."',
      answer: 'Ubiquitous (Omnipresent / Pervasive)',
      factoid: 'Derived from the Latin "ubique", meaning "everywhere". Smartphones and internet access are often described as ubiquitous.',
      category: 'Vocabulary / Linguistics',
      hints: ['Starting with U', 'Omnipresent', 'Everywhere at once'],
    },
  ],
  automoble: [
    {
      id: 'automoble-warmup-1',
      clue: 'An iconic sports car manufactured by Ford since 1964, credited with creating the "pony car" class of sporty coupes with long hoods and short rear decks.',
      answer: 'Ford Mustang',
      factoid: 'Introduced at the New York World\'s Fair in April 1964, Ford forecasted 100,000 sales in year one but sold over 400,000 units.',
      category: 'Muscle & Pony Cars',
      hints: ['Pony car badge', '1964 New York World\'s Fair', 'V8 engine options'],
    },
    {
      id: 'automoble-warmup-2',
      clue: 'A legendary rear-engine, rear-wheel-drive luxury German sports car introduced in 1964 with a distinctive silhouette and boxer engine.',
      answer: 'Porsche 911',
      factoid: 'Originally designated the Porsche 901, the name was changed to 911 after Peugeot protested that it owned trademark rights to three-digit numbers with zero in the middle.',
      category: 'German Sports Cars',
      hints: ['Flat-six boxer engine', 'Stuttgart origin', '901 original name'],
    },
    {
      id: 'automoble-warmup-3',
      clue: 'Introduced by Toyota in 1966, this reliable compact car became the best-selling nameplate in automotive history, surpassing 50 million units sold.',
      answer: 'Toyota Corolla',
      factoid: 'The name "Corolla" is part of Toyota\'s naming tradition of deriving names from the word "crown" (Corolla means small crown in Latin).',
      category: 'Economy & Everyday Cars',
      hints: ['50M+ units sold', 'Best-selling car worldwide', 'Toyota reliability'],
    },
  ],
  botanle: [
    {
      id: 'botanle-warmup-1',
      clue: 'A towering coniferous evergreen tree native to the Sierra Nevada mountains of California, recognized as the largest tree species on Earth by volume.',
      answer: 'Giant Sequoia (Sequoiadendron giganteum)',
      factoid: 'General Sherman, a giant sequoia in California\'s Sequoia National Park, has a volume of approximately 52,500 cubic feet (1,487 cubic meters).',
      category: 'Trees & Forestry',
      hints: ['Sierra Nevada', 'General Sherman tree', 'Thick fire-resistant bark'],
    },
    {
      id: 'botanle-warmup-2',
      clue: 'A perennial herb known for its bright yellow flowers that follow the sun from east to west during the day, a behavior known as heliotropism.',
      answer: 'Sunflower (Helianthus annuus)',
      factoid: 'A single sunflower head is not a single flower, but rather an inflorescence made of thousands of tiny individual flowers called florets.',
      category: 'Flowering Plants',
      hints: ['Heliotropism', 'Helianthus genus', 'Oil and edible seeds'],
    },
    {
      id: 'botanle-warmup-3',
      clue: 'A tropical tree native to Central and South America whose fermented seeds are processed to produce cocoa butter, chocolate liquor, and cocoa powder.',
      answer: 'Cacao Tree (Theobroma cacao)',
      factoid: 'The botanical name "Theobroma" translates literally from ancient Greek to mean "food of the gods".',
      category: 'Tropical Flora',
      hints: ['Food of the gods', 'Chocolate origin', 'Seed pods on trunk'],
    },
  ],
  citadle: [
    {
      id: 'citadle-warmup-1',
      clue: 'The most populous city in the United States, composed of five boroughs: Manhattan, Brooklyn, Queens, The Bronx, and Staten Island.',
      answer: 'New York City',
      factoid: 'More than 800 languages are spoken in New York City, making it the most linguistically diverse metropolitan area in the world.',
      category: 'North America',
      hints: ['Five boroughs', 'Empire State Building', 'Times Square & Broadway'],
    },
    {
      id: 'citadle-warmup-2',
      clue: 'A major international financial center and city-state in Southeast Asia, known as the "Garden City" with iconic attractions like Marina Bay Sands.',
      answer: 'Singapore',
      factoid: 'Singapore is one of only three surviving sovereign city-states in the modern world, alongside Monaco and Vatican City.',
      category: 'Asia',
      hints: ['Merlion symbol', 'Changi Airport', 'Marina Bay Sands'],
    },
    {
      id: 'citadle-warmup-3',
      clue: 'A historic European capital straddling the Seine river, known worldwide as the "City of Light" with iconic landmarks like the Louvre and Notre-Dame.',
      answer: 'Paris, France',
      factoid: 'Paris earned the nickname "City of Light" (La Ville Lumière) both for its leading role during the Age of Enlightenment and for being one of the first European cities to adopt gas street lighting.',
      category: 'Europe',
      hints: ['City of Light', 'Louvre Museum', 'Seine River'],
    },
  ],
  countridle: [
    {
      id: 'countridle-warmup-1',
      clue: 'An archipelago country in East Asia consisting of four main islands: Honshu, Hokkaido, Kyushu, and Shikoku, with Mount Fuji as its highest peak.',
      answer: 'Japan',
      factoid: 'Japan has over 6,800 islands in total, though more than 97% of its land area is comprised of the four primary islands.',
      category: 'East Asia',
      hints: ['Land of the Rising Sun', 'Mount Fuji', 'Tokyo & Kyoto'],
    },
    {
      id: 'countridle-warmup-2',
      clue: 'The sixth-largest country by area in the world, occupying an entire continent between the Indian and Pacific Oceans with unique marsupial wildlife.',
      answer: 'Australia',
      factoid: 'Australia is home to the Great Barrier Reef, the largest coral reef system on Earth and the biggest living structure visible from space.',
      category: 'Oceania',
      hints: ['Canberra capital', 'Outback', 'Great Barrier Reef'],
    },
    {
      id: 'countridle-warmup-3',
      clue: 'Located in North Africa along the Mediterranean and Red Seas, this transcontinental country is home to the Nile River and the Giza Necropolis.',
      answer: 'Egypt',
      factoid: 'The Nile is historically considered the longest river in the world, stretching over 6,650 km (4,130 miles).',
      category: 'North Africa / Middle East',
      hints: ['Cairo capital', 'Nile River', 'Pyramids of Giza'],
    },
  ],
  trordle: [
    {
      id: 'trordle-warmup-1',
      clue: 'Deduction Clue: "A celestial body of hot glowing plasma that generates energy through nuclear fusion at its core." (4 Letters)',
      answer: 'STAR',
      factoid: 'The Sun is the closest star to Earth, located approximately 93 million miles (150 million km) away.',
      category: 'Astronomy Word Puzzle',
      hints: ['4 Letters', 'Starts with S', 'Night sky luminary'],
    },
    {
      id: 'trordle-warmup-2',
      clue: 'Deduction Clue: "The basic structural, functional, and biological unit of all known living organisms." (4 Letters)',
      answer: 'CELL',
      factoid: 'Robert Hooke discovered and coined the term "cell" in 1665 after viewing cork tissue under an early microscope.',
      category: 'Biology Word Puzzle',
      hints: ['4 Letters', 'Starts with C', 'Building block of life'],
    },
    {
      id: 'trordle-warmup-3',
      clue: 'Deduction Clue: "The natural science that studies matter, its fundamental constituents, and its motion through spacetime." (7 Letters)',
      answer: 'PHYSICS',
      factoid: 'From the ancient Greek word "physike", meaning "knowledge of nature".',
      category: 'Science Word Puzzle',
      hints: ['7 Letters', 'Starts with P', 'Newton & Einstein field'],
    },
  ],
};

export function getBrainwaveWarmups(slug: string): BrainwaveWarmupPuzzle[] {
  return BRAINWAVE_WARMUPS[slug] || [];
}
