-- Shared landing-page content for all game families.
-- Covers:
-- - /brainwave and its child routes
-- - /word-games
-- - /number-puzzles
-- - /retro-games
--
-- `is_daily_refresh` marks pages that should behave like a daily puzzle hub or
-- daily game landing page (for example Brainwave routes). Evergreen sections
-- such as word-games, number-puzzles, and retro-games can keep this false.

create extension if not exists pgcrypto;

create type if not exists public.game_section_type as enum (
  'brainwave',
  'word-games',
  'number-puzzles',
  'retro-games'
);

create type if not exists public.game_page_kind as enum (
  'hub',
  'game'
);

create table if not exists public.game_pages (
  id bigint generated by default as identity primary key,
  route_path text not null unique,
  section public.game_section_type not null,
  page_kind public.game_page_kind not null default 'game',
  title text not null,
  meta_description text not null,
  intro_text text not null,
  supporting_copy text not null default '',
  highlights jsonb not null default '[]'::jsonb,
  faq_items jsonb not null default '[]'::jsonb,
  keywords jsonb not null default '[]'::jsonb,
  cta_label text not null default 'Play Now',
  cta_href text not null,
  hero_label text,
  landing_headline text,
  play_notes jsonb not null default '[]'::jsonb,
  is_daily_refresh boolean not null default false,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists game_pages_section_active_sort_idx
  on public.game_pages (section, is_active, sort_order, title);

create index if not exists game_pages_route_path_idx
  on public.game_pages (route_path);

create index if not exists game_pages_daily_refresh_idx
  on public.game_pages (is_daily_refresh, section);

create or replace function public.set_game_pages_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists game_pages_set_updated_at on public.game_pages;

create trigger game_pages_set_updated_at
before update on public.game_pages
for each row
execute function public.set_game_pages_updated_at();

alter table public.game_pages enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'game_pages'
      and policyname = 'Public read game pages'
  ) then
    create policy "Public read game pages"
      on public.game_pages
      for select
      using (true);
  end if;
end $$;
